/*  Define las tablas, inserta los datos de FORMULA 1 */
/*  Fecha  /04/2018 */
/*
source /root/bdd/formula1/defTablasF1.sql;
source /root/bdd/formula1/insertaF1.sql;
*/

SELECT " ******** CARGANDO 2011 ********** " AS MENSAJE;

LOAD DATA INFILE 'compite2011.csv' REPLACE
	 INTO TABLE TCOMPITE
	FIELDS TERMINATED BY ';'  
	LINES TERMINATED BY '\r\n'  ;

SELECT " ******** CARGANDO 2012 ********** " AS MENSAJE;
 LOAD DATA INFILE 'compite2012.csv' REPLACE
	 INTO TABLE TCOMPITE
	FIELDS TERMINATED BY ';'  
	LINES TERMINATED BY '\r\n'  ;
 
SELECT " ******** CARGANDO 2013 ********** " AS MENSAJE;
LOAD DATA INFILE 'compite2013.csv' REPLACE
	 INTO TABLE TCOMPITE
	FIELDS TERMINATED BY ';'  
	LINES TERMINATED BY '\n'  ;
 

SELECT " ******** CARGANDO 2014 ********** " AS MENSAJE;
LOAD DATA INFILE 'compite2014.csv' REPLACE
	 INTO TABLE TCOMPITE
	FIELDS TERMINATED BY ';'  
	LINES TERMINATED BY '\n'  ;

SELECT " ******** CARGANDO 2015 ********** " AS MENSAJE;
LOAD DATA INFILE 'compite2015.csv' REPLACE
	 INTO TABLE TCOMPITE
	FIELDS TERMINATED BY ';'  
	LINES TERMINATED BY '\n'  ;

SELECT " ******** CARGANDO 2016 ********** " AS MENSAJE;
LOAD DATA INFILE 'compite2016.csv' REPLACE
	 INTO TABLE TCOMPITE
	FIELDS TERMINATED BY ';'  
	LINES TERMINATED BY '\n'  ;

SELECT " ******** CARGANDO 2017 ********** " AS MENSAJE;
LOAD DATA INFILE 'compite2017.csv' REPLACE
	 INTO TABLE TCOMPITE
	FIELDS TERMINATED BY ';'  
	LINES TERMINATED BY '\n'  ;

SELECT " ******** CARGANDO 2018 ********** " AS MENSAJE;
LOAD DATA INFILE 'compite2018.csv' REPLACE
	 INTO TABLE TCOMPITE
	FIELDS TERMINATED BY ';'  
	LINES TERMINATED BY '\n'  ;
