use empresa;
drop table if exists TEMPLE;
drop table if exists TDEPTO;
drop table if exists TCENTR;

CREATE TABLE TCENTR
		(	NUMCE	SMALLINT 	NOT NULL,
			NOMCE	VARCHAR(25) NOT NULL UNIQUE,
			SENAS	VARCHAR(25)	NOT NULL default 'Avda. Andalucia',
			PRIMARY KEY(NUMCE) ) ENGINE =INNODB ;
			
CREATE TABLE TDEPTO
		(	NUMDE	SMALLINT NOT NULL PRIMARY KEY,
			NUMCE	SMALLINT NOT NULL DEFAULT 100  ,			 
			DIREC	SMALLINT,
			TIDIR	CHAR(1) CHECK (TIDIR IN ("P", "F")),
			PRESU 	DECIMAL(8,0) NOT NULL,
			DEPDE	SMALLINT,
			NOMDE	VARCHAR(20)	NOT NULL,
		CONSTRAINT  fk_tcentr   
			FOREIGN KEY (NUMCE) REFERENCES TCENTR(NUMCE)
			ON DELETE RESTRICT ON UPDATE CASCADE,
		CONSTRAINT  fk_tdepto  
			FOREIGN KEY (DEPDE) REFERENCES TDEPTO (NUMDE) 
			ON DELETE RESTRICT ON UPDATE CASCADE
		)ENGINE =InnODB ;

CREATE TABLE TEMPLE
	(	NUMEM SMALLINT	NOT NULL  	PRIMARY KEY,
		NUMDE SMALLINT	NOT NULL,
		EXTEL SMALLINT	NOT NULL 
						CHECK (EXTEL >=200),
						CHECK (EXTEL <=910),
		FECNA DATE 	NOT NULL
						CHECK (FECNA >  str_to_date( '1.10.1949','%d.%m.%Y')  ),
		FECIN DATE 	NOT NULL, 
		SALAR DECIMAL (4,0) NOT NULL,
		COMIS DECIMAL (4,0) ,
		NUMHI TINYINT	NOT NULL,
		NOMEM VARCHAR(20)	NOT NULL,
	CONSTRAINT  fk_tcentr2  
		FOREIGN KEY (NUMDE) REFERENCES TDEPTO (NUMDE)
		ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE =InnODB ;
